### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yusuketanno** [yusuketanno/furima_28434#17]
#URL
https://furima-app-28434.herokuapp.com/
#Basic認証用のIDとパスワード
ID:sample@m.com
パスワード:aaa111
#出品者用のメールアドレスとパスワード
ID:sample@k.com
パスワード:aaa222
#購入者用のメールアドレスとパスワード
ID:sample@e.com
パスワード:aaa333
#購入用カードの番号・期限・セキュリティコード
番号：4242424242424242
期限：2月22年
セキュリティコード：123

**Comment by keisukekodama** [comment]
提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**・basic認証が実装されていない**
basic認証を実装しましょう。

修正し次第、以下の完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません

https://docs.google.com/forms/d/e/1FAIpQLSe08G_NmjDTnmZwvplaR5dUh_zUdqH4B4T60lRDIGpzxqBJAg/viewform

**Comment by yusuketanno** [comment]
basic認証
ID:admin
パスワード:2222

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
